"""
main.py - Entry point. Runs all lambda experiments and writes report.md.
Usage: python main.py
"""

import os
import time
import torch

from train    import train, get_loaders
from evaluate import evaluate
from config   import LAMBDAS, REPORT_PATH, PLOT_DIR, DEVICE


def write_report(results):
    lines = [
        "# Self-Pruning Neural Network - Results Report",
        "",
        "## Why L1 on sigmoid gates encourages sparsity",
        "",
        "SparsityLoss = mean( sigmoid(gate_score_i) ) for all i",
        "",
        "The L1 norm has a constant gradient of 1 regardless of gate size.",
        "This keeps pushing gate values all the way to zero (unlike L2 which",
        "slows down near zero and never fully zeroes anything).",
        "",
        "Classification loss pushes gate_scores positive for useful weights.",
        "Sparsity loss pushes ALL gate_scores negative.",
        "Result: useful weights survive (gate near 1), useless ones are pruned (gate near 0).",
        "",
        "---",
        "",
        "## Results",
        "",
        "| Lambda | Test Accuracy (%) | Sparsity Level (%) |",
        "|--------|------------------|--------------------|",
    ]

    for r in results:
        lines.append(
            f"| {r['lambda']:.0e} | {r['accuracy']:.2f} | {r['sparsity']:.2f} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Gate distribution",
        "",
        "See ./plots/gates_lambda_*.png",
        "",
        "A successful result shows:",
        "- Large spike at gate near 0 (pruned weights)",
        "- Cluster near gate 0.8-1.0 (surviving weights)",
        "- Almost nothing in the middle",
        "",
        "---",
        f"Generated by main.py | device: {DEVICE}",
    ]

    os.makedirs(os.path.dirname(REPORT_PATH) or ".", exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\nReport saved -> {REPORT_PATH}")


def main():
    print("\n" + "="*60)
    print("  Self-Pruning Neural Network | CIFAR-10")
    print("="*60)
    print(f"  Device  : {DEVICE}")
    print(f"  Lambdas : {LAMBDAS}")

    os.makedirs(PLOT_DIR, exist_ok=True)
    _, test_loader = get_loaders()

    results = []

    for lam in LAMBDAS:
        t0    = time.time()
        model = train(lam=lam)
        result = evaluate(model, test_loader, lam, save_plot=True)
        results.append(result)

        elapsed = time.time() - t0
        print(f"  Wall time for lambda={lam:.0e}: {elapsed/60:.1f} min\n")

        del model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Final summary
    print("\n" + "="*55)
    print("  FINAL RESULTS")
    print("="*55)
    print(f"  {'Lambda':<10}  {'Test Acc (%)':<15}  {'Sparsity (%)':<15}")
    print(f"  {'-'*8:<10}  {'-'*13:<15}  {'-'*13:<15}")
    for r in results:
        print(f"  {r['lambda']:<10.0e}  {r['accuracy']:<15.2f}  {r['sparsity']:<15.2f}")

    write_report(results)


if __name__ == "__main__":
    main()
